services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chouflihal
      - MONGO_INITDB_ROOT_PASSWORD=chouflihal2024
  
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chouflihal
      ME_CONFIG_MONGODB_ADMINPASSWORD: chouflihal2024
      ME_CONFIG_MONGODB_URL: mongodb://chouflihal:chouflihal2024@mongodb:27017/chouflihal?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:
